[package]
name = "tokiochat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
color-eyre = "0.6.5"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["full"] }
